# NumPy
---

# Содержание

* [Библиотека NumPy](#Библиотека-NumPy)

* [Массивы](#Массивы)

* [Создание массивов](#Создание-массивов)

* [Создание последовательностей](#Создание-последовательностей)

* [Изменение размера / формы массива](#Изменение-размера-/-формы-массива)

* [Срезы](#Срезы)

* [Перебор элементов массива](#Перебор-элементов-массива)

* [Арифметические операции](#Арифметические-операции)

* [Операции сравнения](#Операции-сравнения)

* [Поэлементные функции](#Поэлементные-функции)

* [Функции массивов](#Функции-массивов)

* [Broadcasting](#Broadcasting)

* [Матричные операции](#Матричные-операции)

* [Математика многочленов](#Математика-многочленов)

* [Дополнительно](#Дополнительно)
    * [SciPy](#SciPy)

---

# Библиотека NumPy
---

Библиотека **NumPy** (Numerical Python) - это пакет высокоуровневых математических и числовых функций и инструментов, предназначенных для работы с **массивами numpy**. **Массив numpy** - это высокопроизводительная многомерная структура данных, более эффективная и удобная, чем список Python.

Программа Python, использующая библиотеку **numpy**, может потребовать установки пакета. 

In [2]:
!pip install numpy   # в jupyter notebook numpy уже есть по умолчанию

>Про установку модулей можно посмотреть в 4 файле основного курса

---

Кроме того, программа, использующая пакет, должна включать в себя импорт библиотеки:

In [1]:
import numpy

Тем не менее, для большого количества вызовов функций numpy, становиться утомительно писать numpy.X снова и снова. Вместо этого намного проще использовать alias:

In [3]:
import numpy as np

---
## Массивы
---

Python имеет дело в основном со списками и не имеет собственной структуры массива, поэтому для понимания **массива numpy** важно иметь базовое представление о массивах.  
Одномерный массив можно напрямую сравнить со списком Python, потому что они оба хранят список чисел. Точно так же данные в массиве называются элементами, и доступ к ним осуществляется с помощью скобок **[ ]** .  
Двумерный массив имеет сеточную структуру со строками и столбцами.  
А трехмерный массив можно рассматривать как стек двумерных массивов.  

Массивы Numpy имеют фиксированный размер, индексируются, начиная с 0, и содержат элементы одного типа. Они являются объектами **ndarray** и создаются с помощью функции **np.array()**.

In [4]:
import numpy as np

In [21]:
b = np.array([1, 2, 3, 4])

print(type(b))

<class 'numpy.ndarray'>


Приведенный выше код создает одномерный массив с четырьмя константами.  
Массивы Numpy относятся к измерениям как осям, а количество осей - к рангу. Следовательно, **b - это массив ранга 1**.

---
Существует несколько функций numpy для описания массива и его элементов:

In [7]:
# массив ранга 2
my_arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
])

In [8]:
print(my_arr)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
# обращение к 1 элементу
print(my_arr[1][2])

7


In [15]:
# то же самое, что my_arr[1][2] 
print(my_arr[1, 2])

7


In [16]:
# ранг массива
print(my_arr.ndim)

2


In [17]:
# n строк, m столбцов
print(my_arr.shape)

(2, 4)


In [18]:
# количество элементов
print(my_arr.size)

8


---
## Создание массивов
---

NumPy включает несколько функций для создания массивов. Вы можете инициализировать массивы единицами или нулями, а также создавать массивы, заполненные постоянными или случайными значениями.

In [22]:
# массив из единиц
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [42]:
# массив из нулей
np.zeros(4)

array([0., 0., 0., 0.])

In [31]:
# массив из случайных значений на полуинтервале [0; 1)
np.random.random((2, 3))

array([[0.26841512, 0.28634363, 0.76126739],
       [0.00486321, 0.16736692, 0.80449024]])

In [37]:
# массив заполненный заданным значением
np.full((2, 2), 10)

array([[10, 10],
       [10, 10]])

In [47]:
# массив из неинициализированных элементов
np.empty((2, 2))

array([[6.99596955e-321, 1.37962320e-306],
       [2.22522596e-306, 2.56765117e-312]])

In [59]:
# единицы на главной диагонали со смещением k
np.eye(3, 5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [60]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [61]:
# единичная матрица
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

---
Вы можете дополнительно указать тип данных для элементов массива во время создания.

In [63]:
np.array([1, 2, 3], dtype=np.float32)

array([1., 2., 3.], dtype=float32)

---
Функция **copy()** создает копию массива

In [73]:
a = np.ones(3)
b = a.copy()

a

array([1., 1., 1.])

In [74]:
b

array([1., 1., 1.])

---
Функция **loadtxt()** может быть использована для загрузки данных из файла в массив.  
Функиця **save()** используется для сохранения массива в файл формата **.npy** .   
**savetxt()** - для сохранения в текстовый файл.

In [86]:
x = np.array([
    [ 1,  2,  3],
    [-1, -2, -3],
])

np.savetxt('test.txt', x)

In [87]:
y = np.loadtxt('test.txt')

y

array([[ 1.,  2.,  3.],
       [-1., -2., -3.]])

---
## Создание последовательностей
---

Две полезные функции numpy для создания списка чисел, заполняющих диапазон:  
**np.arange(start, stop, step)** Создает массив numpy с элементами в диапазоне значений от **start** до **stop**, с шагом **step**. Обязательным параметром является только **stop**. Отсутствие начала и шага создает равномерно распределенный диапазон от 0 до **stop**. По сути аналогичен функции **range**.

**np.linspace(start, stop, numvalues)** Создает массив numpy со количеством значений **numvalues**, равномерно распределенными от **start** до **stop**.

In [88]:
import numpy as np

In [89]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [90]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [91]:
np.linspace(0, 10, 6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [94]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

---
## Изменение размера / формы массива
---

Массив numpy может быть изменен по форме и размеру.  
Изменение формы с помощью **np.reshape** возвращает новый массив с измененной формой, а изменение размера с помощью **np.resize** изменяет исходный массив.  
Третья функция **np.ravel** возвращает "плоский" массив, не меняя при этом исходный.

In [1]:
import numpy as np

---

In [2]:
a = np.arange(10)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a.shape

(2, 5)

In [7]:
a.resize(2, 5)

a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

---

In [58]:
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

In [59]:
b.shape

(2, 3)

In [60]:
b.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [61]:
b

array([[1, 2, 3],
       [4, 5, 6]])

---

In [62]:
b.ravel()

array([1, 2, 3, 4, 5, 6])

In [63]:
b

array([[1, 2, 3],
       [4, 5, 6]])

---
**np.transpose** возвращает транспонированную копию массива, не меняя оригинал

In [64]:
b.transpose()  # или b.T

array([[1, 4],
       [2, 5],
       [3, 6]])

---
## Срезы
---

Срез может применяться к массивам numpy, как и к спискам Python, для извлечения подмножества массива.    

Чтобы сделать срез, нужно указать **start:stop:step** подмножества в квадратных скобках.  
Например, **[1: 5: 2]** возвращает элементы 1 и 3.      

In [22]:
import numpy as np

In [23]:
x = np.arange(8)

In [24]:
x[0:4]

array([0, 1, 2, 3])

In [25]:
x[6:]

array([6, 7])

In [26]:
x[:5]

array([0, 1, 2, 3, 4])

---
Срез массива фактически ссылается на элементы массива, поэтому изменение значения в срезе изменяет значение в массиве.

In [28]:
z = x[6:]
z[1] = 100

x

array([  0,   1,   2,   3,   4,   5,   6, 100])

---
Для многомерного массива укажите элементы для каждого измерения, разделенные запятыми.  
Например, **array[0: 2, 1]** возвращает второй элемент в первых двух строках.

Многоточие **...** используется для обозначения выделения по всему измерению.  
Например, **array[…, 2]** возвращает третий элемент каждой строки.

In [29]:
a = np.array([
    [10, 11, 12, 13],
    [20, 22, 23, 25],
])

In [37]:
a[0:1, 1]

array([11])

In [38]:
a[..., 1]

array([11, 22])

In [39]:
a[:, 3]

array([13, 25])

---
## Перебор элементов массива
---

Проводить итерацию массивов можно аналогично спискам:

In [113]:
a = np.array([1, 4, 5])

for x in a:
    print(x)

1
4
5


---
Для многомерных массивов итерация будет проводиться по первой оси, так, что каждый проход цикла будет возвращать «строку» массива:

In [114]:
a = np.array([
    [1, 2], 
    [3, 4], 
    [5, 6],
])

for x in a:
    print(x)

[1 2]
[3 4]
[5 6]


---
Множественное присваивание также доступно при итерации:

In [115]:
a = np.array([
    [1, 2], 
    [3, 4], 
    [5, 6],
])

for x, y in a:
    print(x * y)

2
12
30


---
## Арифметические операции
---

Арифметические операции могут применяться к двум массивам numpy.  
Основные операции используют функции с тем же именем и включают в себя сложение, вычитание, умножение, деление, остаток (деление) и степень.  

Арифметические операторы **+, -, <b>*</b>, /** и <b>**</b> также могут использоваться для выполнения операций с массивами.   

In [40]:
import numpy as np

In [41]:
x = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
])

y = np.array([
    [ 9, 10, 11, 12],
    [13, 14, 15, 16],
])

In [70]:
x + 10

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [44]:
np.add(x, y)   # или x + y

array([[10, 12, 14, 16],
       [18, 20, 22, 24]])

In [49]:
np.remainder(y, x)    # или y % x

array([[0, 0, 2, 0],
       [3, 2, 1, 0]], dtype=int32)

In [50]:
x ** 2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]], dtype=int32)

In [51]:
y - x

array([[8, 8, 8, 8],
       [8, 8, 8, 8]])

In [53]:
x * y   # поэлементное умножение

array([[  9,  20,  33,  48],
       [ 65,  84, 105, 128]])

---
## Операции сравнения
---

Логические сравнения выполняются с использованием <, == и > .  
Например, print(x < y). Логическое сравнение возвращает массив логических значений (True или False).  

In [71]:
import numpy as np

In [75]:
x = np.array([
    [ 1,  2, 93,  4],
    [15, 10,  1, 28],
])

y = np.array([
    [ 9, 10, 11, 12],
    [15, 14, 15, 16],
])

In [76]:
x < y

array([[ True,  True, False,  True],
       [False,  True,  True, False]])

In [77]:
x > 4

array([[False, False,  True, False],
       [ True,  True, False,  True]])

In [78]:
x == y

array([[False, False, False, False],
       [ True, False, False, False]])

---
## Поэлементные функции
---

Некоторые математические функции работают с каждым элементом одного массива numpy.  
Например, вы можете вычислить экспоненту и квадратный корней для элементов в массиве, используя **np.exp()** и **np.sqrt()**.

In [80]:
import numpy as np

In [81]:
x = np.array([
    [1, 2],
    [3, 4],
])

In [82]:
np.exp(x)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [85]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

---
Другие часто используемые поэлементные функции numpy:  
**np.around()** возвращает массив, округленный до необязательно указанного числа десятичных знаков.  
**np.trunc()** возвращает массив с усеченными элементами.  
**np.floor()** возвращает наибольшее целое число, меньшее или равное значению.  
**np.ceil()** возвращает наименьшее целое число, большее или равное значению.  
**np.log()** возвращает натуральный логарифм для каждого элемента.  

>Библиотека numpy также включает множество тригонометрических, гиперболических и других специальных функций, которые работают поэлементно.  
Полный список поддерживаемых функций можно найти на официальном сайте документации: https://numpy.org/doc/stable/reference/routines.math.html#mathematical-functions

---

## Функции массивов
---

Некоторые функции NumPy, которые работают с массивом:  
**np.sum()** возвращает сумму всех элементов.  
**np.prod()** возвращает произведение всех элементов.   
**np.min(), np.max()** возвращает минимальное и максимальное значение в массиве соответственно.   
**np.argmin() и np.argmax()** возвращают индекс минимального или максимального элемента.
**np.cumsum()** возвращает совокупную сумму элементов.  
**np.mean(), np.median()** возвращает среднее и медианное значение для массива соответственно.  

Все упомянутые выше функции имеют необязательный параметр **axis = 1** для значения в каждой строке, **axis = 0** для столбцов.

**np.corrcoef()** возвращает коэффициент корреляции для массива.  
**np.std()** возвращает стандартное отклонение для массива.  

In [86]:
import numpy as np

In [89]:
x = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
])

y = np.array([
    [ 9, 10, 11, 12],
    [13, 14, 15, 16],
])

In [90]:
x.sum(axis=0)

array([ 6,  8, 10, 12])

In [91]:
x.sum()

36

In [92]:
x.sum(axis=1)

array([10, 26])

In [93]:
x.max(axis=1)

array([4, 8])

In [94]:
np.cumsum(y)

array([  9,  19,  30,  42,  55,  69,  84, 100], dtype=int32)

In [95]:
np.corrcoef(y)

array([[1., 1.],
       [1., 1.]])

In [96]:
y.std()

2.29128784747792

---
## Broadcasting 
---

Когда выполняются арифметические операции с массивами разного размера, выполняется операция, называемая **бродкастинг**, для расширения меньшего массива для соответствия большему массиву.  
Бродкастинг, чтобы массивы имели одинаковые размеры или чтобы соответствующий размер был равен 1, чтобы их можно было растянуть. Кроме того, размеры, которые не совпадают, не могут быть растянуты, если один из них не равен 1.

In [97]:
import numpy as np

In [102]:
one_d = np.array([[10]])

two_d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
])

three_d = np.ones((3, 2))

In [103]:
two_d + one_d

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [104]:
one_d + three_d

array([[11., 11.],
       [11., 11.],
       [11., 11.]])

In [105]:
# ValueError
two_d + three_d

ValueError: operands could not be broadcast together with shapes (2,4) (3,2) 

>Больше про бродкастинг в numpy: https://numpy.org/doc/stable/user/basics.broadcasting.html#broadcasting

---

## Матричные операции
---

NumPy обеспечивает много функций для работы с векторами и матрицами. Функция **np.dot()** возвращает скалярное произведение векторов:

In [117]:
import numpy as np

In [118]:
a = np.array([1, 2, 3], float)
b = np.array([0, 1, 1], float)

np.dot(a, b)

5.0

---
Функция dot также может умножать матрицы:

In [120]:
x = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
])

y = np.array([
    [ 9, 10, 11, 12],
    [13, 14, 15, 16],
])

x.dot(y.T)

array([[110, 150],
       [278, 382]])

---
Оператор **@** делает то же самое, что и **np.dot**

In [119]:
a @ b

5.0

In [121]:
x @ y.T

array([[110, 150],
       [278, 382]])

---
Также можно получить скалярное, тензорное и внешнее произведение матриц и векторов.

In [123]:
a = np.array([1, 4, 0])
b = np.array([2, 2, 1])

In [124]:
np.outer(a, b)

array([[2, 2, 1],
       [8, 8, 4],
       [0, 0, 0]])

In [125]:
np.inner(a, b)

10

In [126]:
np.cross(a, b)

array([ 4, -1, -6])

>Для векторов внутреннее и скалярное произведение совпадает.

---

NumPy также предоставляет набор встроенных функций и методов для работы с линейной алгеброй. Это всё можно найти в под-модуле **linalg**. Этими модулями также можно оперировать с вырожденными и невырожденными матрицами.  
Определитель матрицы:

In [144]:
x = np.array([
    [1, 2],
    [3, 4],
])

In [145]:
np.linalg.det(x)

-2.0000000000000004

---
Также можно найти собственный вектор и собственное значение матрицы:

In [148]:
vals, vecs = np.linalg.eig(x)

In [149]:
vals

array([-0.37228132,  5.37228132])

In [150]:
vecs

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

---
Нахождение обратной матрицы:

In [151]:
y = np.linalg.inv(x)

In [152]:
x @ y

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

---
Одиночное разложение (аналог диагонализации не квадратной матрицы):

In [153]:
x = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
])

In [154]:
U, s, Vh = np.linalg.svd(x)

In [155]:
U

array([[-0.37616823,  0.92655138],
       [-0.92655138, -0.37616823]])

In [156]:
s

array([14.22740741,  1.25732984])

In [157]:
Vh

array([[-0.35206169, -0.44362578, -0.53518987, -0.62675396],
       [-0.75898127, -0.3212416 ,  0.11649807,  0.55423774],
       [-0.40008743,  0.25463292,  0.69099646, -0.54554195],
       [-0.37407225,  0.79697056, -0.47172438,  0.04882607]])

---
## Математика многочленов
---

NumPy предоставляет методы для работы с полиномами. Передавая список корней, можно получить коэффициенты уравнения:

In [158]:
np.poly([-1, 1, 1, 10])

array([  1., -11.,   9.,  11., -10.])

>Здесь, массив возвращает коэффициенты соответствующие уравнению: $x^4 - 11x^3 + 9x^2 + 11x - 10$.

---

Может быть произведена и обратная операция: передавая список коэффициентов, функция **root** вернет все корни многочлена:

In [160]:
np.roots([1, 4, -2, 3])

array([-4.5797401 +0.j        ,  0.28987005+0.75566815j,
        0.28987005-0.75566815j])

---
Коэффициенты многочлена могут быть интегрированы. Рассмотрим интегрирование $x^3 + x^2 + x + 1$ в $x^4/4 + x^3/3 + x^2/2 + x + C$. Обычно константа C равна нулю:

In [161]:
np.polyint([1, 1, 1, 1])

array([0.25      , 0.33333333, 0.5       , 1.        , 0.        ])

---
Аналогично, могут быть взяты производные:

In [162]:
np.polyder([1./4., 1./3., 1./2., 1., 0.])

array([1., 1., 1., 1.])

---
Функции **polyadd, polysub, polymul и polydiv** также поддерживают суммирование, вычитание, умножение и деление коэффициентов многочлена, соответственно.  
Функция **polyval** подставляет в многочлен заданное значение. Рассмотрим многочлен $ x^3 - 2x^2 + 2$ при $x = 4$:

In [163]:
np.polyval([1, -2, 0, 2], 4)

34

---
Функция **polyfit** может быть использована для аппроксимации набора значений многочленом заданного порядка по МНК.  
Возвращаемый массив это список коэффициентов многочлена.

In [165]:
x = [1, 2, 3, 4, 5, 6, 7, 8]
y = [0, 2, 1, 3, 7, 10, 11, 19]

np.polyfit(x, y, 2)

array([ 0.375     , -0.88690476,  1.05357143])

---
## Дополнительно
---

NumPy включает еще много других функций о которых мы не упоминали здесь. В частности это функции для работы с дискретным преобразованием Фурье, более сложными операциями в линейной алгебре, тестированием массивов на размер / размерность / тип, разделением и соединением массивов, гистограммами, создания массивов из каких-либо данных разными путями, созданием и оперированием grid-массивов, специальными значениями (NaN, Inf), set-операции, созданием разных видов специальных матриц и вычислением специальных математических функций (Например: функции Бесселя). Также вы можете посмотреть документацию NumPy для более точных деталей. 

https://docs.scipy.org/doc/  
https://numpy.org/doc/stable/index.html


---
### SciPy
---

SciPy очень хорошо расширяет функционал NumPy.   
Функции в каждом модуле хорошо задокументированы во внутренних docstring'ах и в официальной документации. Большинство из них непосредственно предоставляет функции для работы с числовыми алгоритмами и они очень просты в использовании. Таким образом, SciPy может сохранять гигантское количество времени в научных вычислениях, т.к. он обеспечивает уже написанные и тестированные функции.
Мы не будем рассматривать SciPy детально, но таблица ниже покроет некоторые его возможности:

![](https://raw.githubusercontent.com/letimofeev/python_course/main/numpy/images/scipy.png)